frame_dir : ./collected_data/frames
pcd_dir : ./collected_data/pcd
init_frame_number : 0
streamtype : SYStreamTypeEnum.SYSTREAMTYPE_DEPTH  # SYStreamTypeEnum.SYSTREAMTYPE_DEPTH
resolution : SYResolutionEnum.SYRESOLUTION_640_480 # SYResolutionEnum.SYRESOLUTION_640_480
save_pcd : True
save_frame : True 
is_live : False
model_path : "./Models/final_lidar.h5"
input_size : 224
